### ISSUE TITLE
[proof of concept] MD Preview to the side (for ST4065+)

### ISSUE THREAD

**Issue by jrappen** [facelessuser/MarkdownPreview#109]
## Markdown preview to the side

* requires ST4065+ for new HTML sheets
* in Markdown files right-click for context menu and choose preview

## Source files of proof of concept

[mdpreview.zip](https://github.com/facelessuser/MarkdownPreview/files/4162824/mdpreview.zip)

---

[![SublimeHQ Discord](https://img.shields.io/discord/280102180189634562?label=SublimeHQ%20Discord&logo=discord&style=flat-square)](https://discord.gg/D43Pecu)

**Comment by facelessuser** [comment]
I'm assuming this is limited with the type of elements that can be previewed. Supported elements haven't been increased in ST4 right? Tables etc.

**Comment by jrappen** [comment]
I assume only what is listed on [minihtml](https://www.sublimetext.com/docs/3/minihtml.html).

**Comment by jrappen** [comment]
<details>
<summary>Gitlab Flavored Markdown (CLICK FOR PREVIEW)</summary>

<img width="718" alt="image" src="https://user-images.githubusercontent.com/8577450/73899367-b5be7280-488c-11ea-9f6d-143a28cdc228.png">

</details>

compare <https://gitlab.com/gitlab-org/gitlab/raw/master/doc/user/markdown.md>

**Comment by facelessuser** [comment]
I haven't checked out the proof of concept, but the limitations may really...well limit the usefulness...

In theory, the idea is cool though.

**Comment by facelessuser** [comment]
Doesn't this package support in Sublime previews? https://github.com/math2001/MarkdownLivePreview

**Comment by jrappen** [comment]
haven't used that

**Comment by facelessuser** [comment]
I always wanted to do previews in Sublime, but the limitations has held me back. Mdpopups helps a bit with some of the limitations, but unfortunately there are many that still hold it back from being a real viable solution.

I know that other package ran with the in editor approach. I'd be interested to see if people still find it useful long term. I'm not against adding something like this per se, but I'm often using things like tables etc. Which just won't render.

Mdpopups works great though when you play directly to its strengths, which is why I use it to generate content from Markdown, but the Markdown is always written with the limitations in mind.

**Comment by jrappen** [comment]
Unrelated to Sublime Text, but this browser extension is kinda nice:

https://github.com/painyeph/GitLabMarkdownViewer

I listed known issues on painyeph/GitLabMarkdownViewer#13

**Comment by facelessuser** [comment]
Pretty cool project. I'm surprised that don't just use the Gitlab API. Doing it locally is cool if you can pull off all the features, but it's tough to maintain 1:1 parity that way unless you are using everything they are using. But it's a really cool effort.

**Comment by facelessuser** [comment]
As there is no actionable item here for Markdown Preview, closing this issue. Very cool though :slightly_smiling_face: .

@gir-bot remove S: triage
