### ISSUE TITLE
Not rendering content properly when using livereload

### ISSUE THREAD

**Issue by brupelo** [facelessuser/MarkdownPreview#112]
Hi, really cool package this one, thanks! After testing the other available ones for ST
it seems this one is the most promising/mature.

This is the first time I'm using so I'm sorry if I'm opening a github issue with a well-known issue. I was trying to learn how to use your package with `livereload` and I've faced some really annoying problems.

Please take a look to the video (specially at ~00:08): https://dl.dropboxusercontent.com/s/54saxlsn6k3ux34/2020-03-18_16-08-42.mp4

As you can see, the sequence you can follow to reproduce would be:

1) save/render 
2) delete the `------------` + save/render
3) ctrl+z + save/render

As you can see, the render won't be correct when saved... even if you save it few times. Is this a well known issue? I've followed the advices provided in the docs, ie: 
`Simple Reload with delay 400ms`

Could you please advice?

**Requirements:**

- windows7
- chrome 80.0.3987.132 (Build oficial) (64 bits)
- markdownPreview v2.2.5
- livereload 0.1.3

**Comment by stephanmg** [comment]
Is this project not maintained anymore?

**Comment by facelessuser** [comment]
It is maintained, but I support a number of projects, so some issues can go unnoticed by accident.

**Comment by stephanmg** [comment]
> It is maintained, but I support a number of projects, so some issues can go unnoticed by accident.

That's great, I really enjoy the MarkdownLivePreview in Sublime.

**Comment by facelessuser** [comment]
None taken. Some extensions need less work than others, but I'm also not great at multitasking, so my focus can go very intense on certain projects causing some to get less love. I'm currently very focused on a heavy refactor of the ColorHelper plugin. I do have plans to update some of the dependencies under the hood for this plugin and such sometime soon-ish.

**Comment by facelessuser** [comment]
Closing this issue as a duplicate of #74. I would check out that issue and see if it answers the original question. This issue is kind of stale at this point, sorry I missed it.

Livereload is a bit finicky at times. TBH, I don't use the "live" mode much, and the implementation was inherited when I took over the project. Some improvements have been made over time, but it seems it's never exactly perfect and can require some fiddling. I am happy to improve docs if there are gaps there.

@gir-bot remove S: triage
@gir-bot add S: duplicate
