### ISSUE TITLE
Preview command generates files but does not show in browser

### ISSUE THREAD

**Issue by ArnaudBru** [facelessuser/MarkdownPreview#170]
When I run the preview in browser command from SublimeText, I get a file not found error.

 The file is created in `/tmp` but I cannot open it in my browser from there, this is likely due to the fact that Linux supports "mount namespaces" which allow different processes to have different views of what's mounted where (e.g. this is how containers such as Docker or LXC are implemented).

Firefox was installed through the snap system, which isolates each app in its own container with limited access to the real system – what Firefox sees as /tmp inside the container corresponds to /tmp/snap.firefox/tmp (or /tmp/snap-private-tmp/snap.firefox/tmp) outside the container.

This issue happens with
Ubuntu 22.04
Firefox 116.0.3 (64-bit)
Sublime Text Build 4152
MarkdownPreview v2.4.3

**Comment by facelessuser** [comment]
I am open to suggestions. If you know of a workable solution, a PR would be appreciated.

**Comment by facelessuser** [comment]
This is what we currently do. Linux seems to love to make this increasingly more difficult to abstract: https://github.com/facelessuser/MarkdownPreview/blob/master/browser.py#L60.

**Comment by facelessuser** [comment]
I guess this isn't a "browser opening" issue as much as it is a tmp file creation issue. As I have no way of knowing what specific tmp a browser can see or does not see, we'd have to make some tmp file relocation feature where the user can specify where they want their tmp to be so their browser can see it. I'm not sure I'm interested in jumping through hoops to try and automatically figure out what specific tmp we should use, so having the user specify it is probably going to be the compromise.

If anyone wants to tackle this, I'm happy to take a PR, otherwise, I'll put it on my list and see when I have time to update this.

**Comment by facelessuser** [comment]
@ArnaudBru I forgot we already abstracted temp files, try out this setting: https://github.com/facelessuser/MarkdownPreview/blob/master/MarkdownPreview.sublime-settings#L317

**Comment by facelessuser** [comment]
As it appears the temp folder can already be controlled, closing this as no change. If this is not sufficient feel free to reopen, but please provide details as to why it is not sufficient.

**Comment by agnostic-apollo** [comment]
For Ubuntu `22.04` where firefox is provided by snap, I added `/run/user/1000 /home/<user>/tmp none bind 0 0` to `/etc/fstab` and then ran `mkdir -p ~/tmp; sudo mount ~/tmp` so that it gets mounted without a reboot. The `<user>` needs to be replaced by your username and replace `1000` if your uid is different (`id -u`). `/run/user/1000` is basically a `tmpfs` for user `1000` and will be cleared automatically on reboot (`mount | grep tmpfs`), so better to use it than using a real directory which will have to be cleared manually or some other way.

Note that for snaps by default, only directories under home (`$HOME`) are readable if they do not start with a dot `.` (non-hidden), so do not try to use `~/.tmp` or directly use `/run/user/1000` path. Also we need to create a `bind` mount to `/run/user/1000`, as a symlink will not work as `realpath` will be checked.

Add `"path_tempfile": "/home/<user>/tmp/MarkdownPreview"` to MarkdownPreview settings. It doesn't expand environmental variables like `$HOME`, so will require hard coding the path.

Related https://bugs.launchpad.net/ubuntu/+source/libreoffice/+bug/1790608 and https://askubuntu.com/a/1238219

Hopefully, this helps others.
