### ISSUE TITLE
Glyph appear on anchor

### ISSUE THREAD

**Issue by 4sStylZ** [facelessuser/MarkdownPreview#19]
Hi,

That can be a setting error of my configuration. I have used MarkdownPreview many times and for some reason he is now showing strange glyph in the <a> anchor link.

![example](http://i.imgur.com/K50KeRD.png)

Sorry for the blur but I don’t own the document.

Any idea ?

**Comment by facelessuser** [comment]
You have any errors in your web browser console? As I recall, it's had header anchors for a long time.  I don't think that has changed, but if there is a problem, it is most likely because it can find the icon with the glyph.  Unfortunately I don't have enough information to debug this for you.

Are you using a custom CSS or the default?  Do you have custom settings for MarkdownPreview, or are you using stock.  What kind of errors are you seeing in the console?  Are you using the`github` parser or the `markdown` (Python Markdown)?

**Comment by facelessuser** [comment]
As there hasn't really been a response to this, I will close this issue.

**Comment by 4sStylZ** [comment]
Sorry for the delay,

It was clearly an issue because of a custom .css file who haven’t the font-awesome font.
Thank you for your time.
