### ISSUE TITLE
How to deal with MIME type issue with css

### ISSUE THREAD

**Issue by 4sStylZ** [facelessuser/MarkdownPreview#31]
Hi, 

I have a custom css.

* Raw : https://framagit.org/4sStylZ/markdown-preview-css/raw/master/markdown-preview.css
* Normal view : https://framagit.org/4sStylZ/markdown-preview-css/blob/master/markdown-preview.css

I want to use store it on gitlab and set the raw link in the Markdown Preview package settings but I have this message : 

`Refused to apply style from 'https://framagit.org/4sStylZ/markdown-preview-css/raw/master/markdown-preview.css' because its MIME type ('text/plain') is not a supported stylesheet MIME type, and strict MIME checking is enabled.`

Any suggestion for correct it the proper way ?

Thank you.

**Comment by hadisfr** [comment]
Hi!

It's something related to GitLab. It seems they serve some files as `text/plain` for security reasons:

> The restricted content types in RawController are a security feature. Without it an attacker can trick the browser of a victim into executing code served by a GitLab server.

While any CSS should have got `text/css` _Content-type_ to be rendered in browsers. See [gitlab-org/gitlab-ce#9079](https://gitlab.com/gitlab-org/gitlab-ce/issues/9079).

You should host your stylesheets elsewhere so that it can be served with correct MIME-type. Perhaps using _GitLab pages_ and use page's link solves the issue, too, if your site is using GitLab Enterprise Edition.

**Comment by facelessuser** [comment]
Thanks for answering this @hadisfr. I'll consider this issue closed.
