### ISSUE TITLE
Emoji alpha codes not working

### ISSUE THREAD

**Issue by akaleeroy** [facelessuser/MarkdownPreview#39]
Several of the [EmojiOne alpha codes](/emojione/emojione/blob/master/extras/alpha-codes/eac.csv#L2482) (aka shortcodes) won't render, and you never know which will work and which won't.

Is EmojiOne out of date or what?

**Comment by facelessuser** [comment]
Can you give me some actual markdown examples of something that doesn't work? Right now I don't understand what your issue is.

Also, read pymdown-extensions' emoji extension documentation. Not everything inherent with emojione is supported, such as converting ASCII smilies etc. So if you see a discrepancy with what the emoji extension describes as supported and the actual rendering, please provide such an example.

**Comment by facelessuser** [comment]
Also, make sure you are using the appropriate CSS for emojione, if you are not, you'll need to update your CSS settings.  For further help, you'll also need to provide your related settings.

**Comment by akaleeroy** [comment]
Sorry, there's been a mix-up with my settings file!

I _thought_ I had set `pymdownx.emoji.emojione` but it was set to the Github set of emojis `pymdownx.emoji.gemoji`

Switching to emojione fixes the issue, full set of alpha codes render emojis as expected.
I'll include my current emoji settings in _MarkdownPreview.sublime-settings -– User_

```plain
{
  "markdown_extensions": [
    // Other extensions, ommitted here
    {
      "pymdownx.emoji": {
        // Provide EmojiOne emojis
        "emoji_index": { "!!python/name": "pymdownx.emoji.emojione" },
        "emoji_generator": { "!!python/name": "pymdownx.emoji.to_png" },
        "alt": "short",
        "options": {
          "attributes": {
            "align": "absmiddle",
            "height": "20px",
            "width": "20px"
          }
        }
      }
    }
  ]
}
```

**Comment by facelessuser** [comment]
That sounds more like it :smile:. Glad you figured it out.
