### ISSUE TITLE
This package disappeared from my Package Control

### ISSUE THREAD

**Issue by DannyBen** [facelessuser/MarkdownPreview#9]
Using Sublime 2, this is what happened to me today:

1. I opened the Default Settings of Markdown Preview, and saw the file is empty (yesterday it was ok).
2. I removed the package via Package Control
3. I tried to reinstall it, only to see it is no longer available in my "Install Package" list

**Comment by facelessuser** [comment]
Sublime Text 2 is no longer supported.  I no longer support ST2 on any of my plugins anymore.  It is ST3 only moving forward.  I don't have the bandwidth to support more than one with all of the Sublime plugins I support.

You are welcome to add the old legacy ST2 branch to your own local, custom package control channel and try that, or install locally and run `Package Control: Satisfy Dependencies`, and then restart.  That should work I believe.

**Comment by zsiegel92** [comment]
I am using ST3 and something similar happened to me today!

All of a sudden, MathJax stopped rendering. I checked my user settings to verify they had not changed, and I noticed the "...Application Support/Sublime Text  3/Packages/MarkdownPreview" directory did not exist!

Markdown opens a file in that folder when I select "Sublime Text > Preferences > Package Settings > Markdown Preview > Settings - Default" (specifically, the file MarkdownPreview.sublime-settings). However, this folder does not exist on my filesystem.

What is going on? Please help. I need to render Markdown with MathJax!

**Comment by facelessuser** [comment]
> I noticed the "...Application Support/Sublime Text 3/Packages/MarkdownPreview" directory did not exist!

It's probably in `Application Support/Sublime Text 3/Installed Packages/MarkdownPreview.sublime-package`.

> What is going on? Please help. I need to render Markdown with MathJax!

This is a major release that was meant to clean things up and make it easier for me to maintain since I've taken over maintenance.  There have also been some improvements, but all of this comes at the cost of change. Things are a little different, so please read the documentation: https://facelessuser.github.io/MarkdownPreview/extras/#mathjax-support.

If you have any more issues, please create a **new** issue with your specific issue.

**Comment by facelessuser** [comment]
As this question has been answered, I am closing the issue.
