### ISSUE TITLE
MarkdownPreview in Sublime-text3 opens Signal app, instead of browser tab

### ISSUE THREAD

**Issue by glicerico** [facelessuser/MarkdownPreview#90]
I installed MarkdownPreview in `Sublime Text3` with no trouble.
When I try to generate a preview of my markdown file in a browser following [these](https://facelessuser.github.io/MarkdownPreview/usage/) instructions, the system opens my Signal messenger app, instead of a tab in the browser.

Any idea if this is an issue with my configuration or a conflict with Signal?
I'm running Ubuntu 18.04LTS.

**Comment by facelessuser** [comment]
I am going to need specifics on your related settings. I am on The same Ubuntu version, and it works well for me. If your system default to the wrong application for HTML documents, it may be something you need to adjust in Ubuntu, or you may need to manually point it at the application to use in the Markdown Preview settings.

**Comment by facelessuser** [comment]
Most likely `Signal` is set to open HTML files on your system for some reason. You can either change that in your Ubuntu settings, or force Markdown Preview to use the application of your choice. You can read this section (near the end) which will point you to the `browser` option to set a specific browser instead of detecting the default.

**Comment by glicerico** [comment]
Thanks! That was the problem, and it's solved after I set a browser as default app to open html files
